name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        working-directory: packages/lib
        run: yarn build

      - name: Publish
        run: npm publish --provenance --access public
        working-directory: packages/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
